---UPDATE OLD WEIGHT---
UPDATE ASSIGNMENT  
SET weight = 50
WHERE courseCode = 'IT403' AND assignmentNumber = 1; 
--CREATE NEW ASSIGNMENTS
INSERT INTO ASSIGNMENT 
		(courseCode, weight, dueDate)
		VALUES('IT403',25,'2023-04-15')
INSERT INTO ASSIGNMENT 
		(courseCode, weight, dueDate)
		VALUES('IT403',10,'2023-04-15')
INSERT INTO ASSIGNMENT 
		(courseCode, weight, dueDate)
		VALUES('IT403',15,'2023-04-15')

SELECT * FROM ASSIGNMENT


---DELETE ASSIGNMENT 2
DELETE FROM ASSIGNMENT 
WHERE courseCode = 'IT403' AND assignmentNumber = 2;
SELECT * FROM ASSIGNMENT

---DELETE ASSIGNMENT 3
DELETE FROM ASSIGNMENT 
WHERE courseCode = 'IT403' AND assignmentNumber = 3;
SELECT * FROM ASSIGNMENT
